[shell]
program		= "/bin/zsh"
#args		= [ "--login" ]

[env]
TERM		= "xterm-256color"

[window]
dimensions	= { columns = 120, lines = 32 }
padding	       = { x = 5, y = 5 }
decorations	= "none"
opacity		= 0.8
blur		= true

[scrolling]
history = 65535

[font]
normal		= { family = "Iosevka Nerd Font", style = "Regular" }
bold		= { family = "Iosevka Nerd Font", style = "Bold" }
italic		= { family = "Iosevka Nerd Font", style = "Italic" }
bold_italic	= { family = "Iosevka Nerd Font", style = "Bold Italic"}
size		= 12.5
offset		= { x = 0, y = 0 }
glyph_offset	= { x = 0, y = 0 }

[colors.primary]
background	= '#121418'
foreground	= '#E5E8EC'
#dim_foreground		= '#E5E8EC'
#bright_foreground	= '#F4F6F9'
#dim_background		= '#121923'
#bright_background	= '#323943'

# Normal colors
[colors.normal]
black		= '#121418'
red		= '#EC5564'
green		= '#9ED36A'
yellow		= '#FECD57'
blue		= '#5E9CEA'
magenta		= '#AC92EA'
cyan		= '#46CEAD'
white		= '#E5E8EC'

# Bright colors
[colors.bright]
black		= '#323943'
red		= '#F76D82'
green		= '#B4E080'
yellow		= '#FCD277'
blue		= '#73B1F4'
magenta		= '#B3A5EF'
cyan		= '#62DDBD'
white		= '#F4F6F9'

# Dim colors
[colors.dim]
black		= '#000000'
red		= '#D94452'
green		= '#8AC054'
yellow		= '#F5BA45'
blue		= '#4B89DA'
magenta		= '#967ADA'
cyan		= '#35BB9B'
white		= '#CBD0D8'

[colors]
# indexed_colors = [
#	{ index 16, color = "#FFFFFF" }
# ]
draw_bold_text_with_bright_colors = true

[bell]
animation	= "EaseOutExpo"
duration	= 0
color		= '#73B1F4'
#command		= { program = "notify-send", args = ["alacritty", "bell"] }

[mouse]
hide_when_typing	= true
bindings	= [
  { mouse = "Right", action = "Copy" },
  { mouse = "Middle", action = "Paste" }
]

[cursor]
blink_interval	= 500
blink_timeout	= 0

[cursor.style]
shape		= "Block"
blinking	= "Always"

[keyboard]
bindings = [
  { key = 'V', mods = "Control|Shift", action = "Paste" },
  { key = 'C', mods = "Control|Shift", action = "Copy" },
  { key = 'Insert',    mods = 'Shift',         action = 'PasteSelection'              },
  { key = 'Key0',      mods = 'Control',       action = 'ResetFontSize'               },
  { key = 'Equals',    mods = 'Control',       action = 'IncreaseFontSize'            },
  { key = 'Plus',      mods = 'Control',       action = 'IncreaseFontSize'            },
  { key = 'Minus',     mods = 'Control',       action = 'DecreaseFontSize'            },
  { key = 'F11',       mods = 'None',          action = 'ToggleFullscreen'            },
  { key = 'Paste',     mods = 'None',          action = 'Paste'                       },
  { key = 'Copy',      mods = 'None',          action = 'Copy'                        },
  # { key = 'L',         mods = 'Control',       action = 'ClearLogNotice'              },
  # { key = 'L',         mods = 'Control',       chars = '\x0c'                       },
  { key = 'PageUp',    mods = 'None',          action = 'ScrollPageUp',   mode = '~Alt'  },
  { key = 'PageDown',  mods = 'None',          action = 'ScrollPageDown', mode = '~Alt'  },
  { key = 'Home',      mods = 'Shift',         action = 'ScrollToTop',    mode = '~Alt'  },
  { key = 'End',       mods = 'Shift',         action = 'ScrollToBottom', mode = '~Alt'  }
]
